freshday/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),  # 富文本编辑模块
    path('user/', include('user_fd.urls')),
    path('order/', include('order_fd.urls')),
    path('', include('goods_fd.urls')),
    path('search/', include('haystack.urls')),  # haystack
    path('test/', include('tem.urls')),
    path('cart/', include('shopcart.urls')),
]

goods_fd/urls.py
from django.urls import path, re_path, include
from . import views
app_name = 'goods'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('goods/<str:goods_id>/', views.DetailView.as_view(), name='detail'),
    path('list/<str:type_id>/<str:page>/', views.ListView.as_view(), name='list'),
    path('page/<int:p>', views.pagedex, name='page'),
]

order_fd/urls.py
from django.urls import path, re_path, include
from . import views
app_name = 'order'
urlpatterns = [
    # path('infor/', views.info, name='infor'),
    path('infor/', views.OrderPlaceView.as_view(),name='infor'),
    path('commit/', views.OrderCommitView.as_view(), name='commit'),
    path('pay/', views.OrderPayView.as_view(), name='pay'),
    path('check/', views.CheckPayView.as_view(), name='check'),
    path('comment/<str:order_id>', views.CommentView.as_view(), name='comment')
]

shopcart/urls.py
from django.urls import path, re_path, include
from . import views
app_name = 'cart'
urlpatterns = [
    path('add/', views.CartAddView.as_view(), name='add'),
    path('', views.CartInfoView.as_view(), name='info'),
    path('delete/', views.CartDeleteView.as_view(), name='delete'),
    path('update/', views.CartUpdateView.as_view(), name='update'),
]

tem/urls.py
from django.urls import path, include
from tem import views
urlpatterns = [
    path('name/', views.test),
    path('age/',views.t2),
]

user_fd/urls.py
from django.urls import path, re_path, include
from django.contrib.auth.decorators import login_required
# 如果用户没有登录，会重定向到 settings.LOGIN_URL ，
# 并传递绝对路径到查询字符串中。例如： /accounts/login/?next=/polls/3/ 。如果用户已经登录，则正常执行视图。
from . import views
app_name = 'user'
# 登陆验证,视图继承LoginRequiredMixin
urlpatterns = [

    path('', views.UserInfoView.as_view(), name='info'),
    path('order/<str:page>/', views.UserOrderView.as_view(), name='order'),
    path('address/', views.UserAddressView.as_view(), name='address'),
    path('register/', views.Register.as_view(), name='register'),
    path('active/<str:token>/', views.ActiveView.as_view(), name='active'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout')

]


 # 使用login_required装饰器
# urlpatterns = [
#
#     path('', login_required(views.UserInfoView.as_view()), name='info'),
#     path('order/', login_required(views.UserOrderView.as_view()), name='order'),
#     path('address/', login_required(views.UserAddressView.as_view()), name='address'),
#     path('register/', views.Register.as_view(), name='register'),
#     path('active/<str:token>/', views.ActiveView.as_view(), name='active'),
#     path('login/', views.LoginView.as_view(), name='login'),
#
# ]

templates/base.html
{# 首页  注册 登陆 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{#网页顶部文件块javascrip文件#}
    {% block topfile %}{% endblock topfile %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
{#             Web 请求的认证¶#}
{#                Django 使用 sessions 和中间件将身份验证系统挂接到请求对象中。#}
{##}
{#                它们在每次请求中都会提供 request.user 属性。如果当前没有用户登录，这个属性将会被设置为 AnonymousUser ，否则将会被设置为 User 实例。#}
{##}
{#                你可以使用 is_authenticated 区分两者 #}
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username  }}</em>
                <a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:info' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}
{# 网页顶部搜索框 #}
{% block search_bae %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form method="get" action="{% url 'haystack_search' %}">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:info' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bae %}
{# 网页主体内容 #}
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{# 网页底部HTML元素块 #}
{% block bottom %}{% endblock bottom %}
{# 网页底部引入文件 #}
{% block bottomfile %}{% endblock bottomfile %}
</body>
</html>

templates/base_detail_list.html
{# 详情页 列表页 #}
{% extends 'base.html' %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for t in types %}
					<li><a href="{% url 'goods:list' t.id 1 %}" class="{{ t.logo }}">{{ t.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
{#				<li class="interval">|</li>#}
{#				<li><a href="">手机生鲜</a></li>#}
{#				<li class="interval">|</li>#}
{#				<li><a href="">抽奖</a></li>#}
			</ul>
		</div>
	</div>
    {# 详情页 列表页 主体内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/basetest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block name %}
    name is {{ name }}<br>
    request{{ request }}<br>
    user :{{ user }}<br>
    {{ request.user }}<br>
    {{ request.site}}<br>
{% endblock name %}
{% block age %}
{% endblock age %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
<head>
    {% block title %}天天生鲜-首页{% endblock title %}
    {% block topfile %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    {% endblock topfile %}
</head>
<body>
{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
{#				<li><a href="{% url 'goods:index' %}">首页</a></li>#}
{#				<li class="interval">|</li>#}
{#				<li><a href="">手机生鲜</a></li>#}
{#				<li class="interval">|</li>#}
{#				<li><a href="">抽奖</a></li>#}
			</ul>
		</div>
	</div>
	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			<li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for g in goods_banners %}
				<li><img src="{{ g.image.url }}" alt="幻灯片"></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for p in promotion_banners %}
			<a href="#"><img src="{{ p.image.url }}"></a>
		    {% endfor %}
        </div>
	</div>
    {% for type1 in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<a href="{% url 'goods:list' type1.id 1 %}" > <h3 class="fl" id="model0{{ forloop.counter }}">{{ type1.name }}</h3> </a>
			<div class="subtitle fl">
				<span>|</span>
                {% for i in type1.title_banner %}
				<a href="{% url 'goods:detail' i.sku.id %}">{{ i.sku.name }}</a>
                {% endfor %}
			</div>
			<a href="{% url 'goods:list' type1.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><a href="{% url 'goods:list' type1.id 1 %}"><img src="{{ type1.image.url }}"></a></div>
			<ul class="goods_list fl">
                {% for i in type1.image_banner  %}
				<li>
					<h4><a href="{% url 'goods:detail' i.sku.id %}">{{ i.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' i.sku.id %}"><img src="{{ i.sku.image.url }}"></a>
					<div class="prize">¥ {{ i.sku.price }}</div>
				</li>
                    {% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	<script type="text/javascript" src="{% static 'js/slideshow.js' %}"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
</body>
</html>

templates/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-商品列表{% endblock title %}
</head>
<body>
{% block body %}
    {% csrf_token %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for t in types %}
					<li><a href="{% url 'goods:list' t.id 1 %}" class="{{ t.logo }}">{{ t.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
{#				<li><a href="">首页</a></li>#}
{#				<li class="interval">|</li>#}
{#				<li><a href="">手机生鲜</a></li>#}
{#				<li class="interval">|</li>#}
{#				<li><a href="">抽奖</a></li>#}
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for n in new_skus %}
					<li>
						<a href="{% url 'goods:detail' n.id %}"><img src="{{ n.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' n.id %}">{{ n.name }}</a></h4>
						<div class="prize">￥{{ n.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id skus_page.number %}?sort=default"{% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id skus_page.number %}?sort=price"{% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id skus_page.number %}?sort=hot"{% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
            {% for sp in skus_page %}
				<li>
					<a href="{% url 'goods:detail' sp.id %}"><img src="{{ sp.image.url }}"></a>
					<h4><a href="detail.html">{{ sp.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sp.price }}</span>
						<span class="unit">{{ sp.price }}/{{ sp.units }}</span>
						<a href="javascript:;" class="add_goods" id="add_goods" sku_id="{{ sp.id }}" title="加入购物车"></a>
					</div>
				</li>
            {% endfor %}
			</ul>

			<div class="pagenation">
{#             page属性有上页返回True  ?sort 使得排序不变#}
                {% if  skus_page.has_previous %}
                <a href="{% url 'goods:list' type.id skus_page.previous_page_number %}?sort={{ sort }}">上一页</a>
                {% endif %}
{#                Page.paginator¶ 关联的 Paginator 对象。#}
                {% for p in skus_page.paginator.page_range %}
{#                    如果是当前页class = 'active'#}
                    {% if p == skus_page.number %}
				<a href="{% url 'goods:list' type.id p %}?sort={{ sort }}" class="active">{{ p }}</a>
                    {% else %}
				<a href="{% url 'goods:list' type.id p %}?sort={{ sort }}">{{ p }}</a>
                    {% endif %}
                {% endfor %}
{#            有下一页返回True#}
            {% if skus_page.has_next %}
				<a href="{% url 'goods:list' type.id skus_page.next_page_number %}?sort={{ sort }}">下一页></a>
            {% endif %}

			</div>
		</div>
	</div>
{% endblock body %}
{% block bottomfile %}
    <div class="add_jump"></div>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
    {#alert('脚本执行')#}
        update_goods_amount()
        // 计算商品的总价格
        function update_goods_amount() {
            // 获取商品的单价和数量
            price = $('.show_pirze').children('em').text()
            count = $('.num_show').val()
            // 计算商品的总价
            price = parseFloat(price)
            count = parseInt(count)
            amount = price*count
            // 设置商品的总价
            $('.total').children('em').text(amount.toFixed(2)+'元')
        }
        // 获取add_cart div元素左上角的坐标
		var $add_x = $('#add_goods').offset().top;
		var $add_y = $('#add_goods').offset().left;

        // 获取show_count div元素左上角的坐标
		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;


		$('.add_goods').click(function(){
            // 获取商品id和商品数量
            {#alert('添加购物车')#}
            sku_id = $(this).attr('sku_id') // attr prop
            count = 1
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            // 组织参数
            params = {'sku_id':sku_id, 'count':count, 'csrfmiddlewaretoken':csrf}
            // 发起ajax post请求，访问/cart/add, 传递参数:sku_id count
            $.post('{% url "cart:add" %}', params, function (data) {
                if (data.res == 5){
                    // 添加成功
                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
                    $(".add_jump").stop().animate({
                        'left': $to_y+7,
                        'top': $to_x+7},
                        "fast", function() {
                            $(".add_jump").fadeOut('fast',function(){
                                // 重新设置用户购物车中商品的条目数
                                $('#show_count').html(data.total_count);
                            });
			        });
                }
                else{
                    // 添加失败
                    alert(data.errmsg)
                }
            })
		})
	</script>
{% endblock %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

</body>

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bae %}{% endblock search_bae %}
<body>
    {% block body %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post">{% csrf_token %}

						<input type="text" name="username" class="name_input"value="{{ username }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remenber" {{ checked }}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
        var e ={{ errmsg }}
        <script>if ({{ errmsg }}) { alert({{ errmsg }})} </script>
{% endblock body %}
	
</body>
</html>

templates/pagetest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for p in page %}
<li>
    {{ p.id }}
</li>
<li>
    {{ p.name }}
</li>
{% endfor %}
</body>
</html>

templates/place_order.html
{% extends 'base_no_cart.html' %}

{% load staticfiles %}
{% block title %}天天生鲜-提交订单{% endblock title %}
<body>
{% block pagetitle %}提交订单{% endblock pagetitle %}
{% block body %}
    {% csrf_token %}
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
    {% for ad in address %}
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" name="addr_id" value="{{ ad.id }}"{% if ad.is_default %}checked="checked"{% endif %} >{{ ad.address }} （{{ ad.receiver }} 收）联系方式： {{ ad.phone }}</dd>
		</dl>
        {% endfor %}
		<a href="{% url 'user:address' %}" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" value="1" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style" value="2">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style" value="3">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style" value="4">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
        {% for sku in skus %}
		<ul class="goods_list_td clearfix">
			<li class="col01">{{ forloop.counter }}</li>
			<li class="col02"><img src="{{ sku.image.url }}"></li>
			<li class="col03">{{ sku.name }}</li>
			<li class="col04">{{ sku.units }}</li>
			<li class="col05">{{ sku.price }}元</li>
			<li class="col06">{{ sku.count }}</li>
			<li class="col07">{{ sku.amount }}元</li>
		</ul>
        {% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ total_count }}</em>件商品，总金额<b>{{ total_price }}</b></div>
			<div class="transit">运费：<b>{{ transit_price }}</b></div>
			<div class="total_pay">实付款：<b>{{ total_pay }}</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">

		<a href="javascript:;" sku_ids="{{ sku_ids }}"  id="order_btn">提交订单</a>
	</div>	
{% endblock body %}
{% block bottom %}
	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>
{% endblock bottom %}
{% block bottomfile %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
		$('#order_btn').click(function() {
		    //获取用户选择的地址，支付方式，要购买的商品id字符串
            addr_id = $('input[name="addr_id"]:checked').val()
            pay_method = $('input[name="pay_style"]:checked').val()
            sku_ids = $(this).attr('sku_ids')
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            {#csrf = 'NKJgeAsHX9IrP9bHYaIAUzFrLllujNMHgFef5bEM9AmoYSAXqkUZpCA2XUSOLZTh'#}
            {#alert(csrf)#}
            {#alert(addr_id+':'+pay_method+":"+sku_ids)#}
            //组织参数
            params = {'addr_id':addr_id, 'pay_method':pay_method, 'sku_ids':sku_ids, 'csrfmiddlewaretoken':csrf}
            //发起ajax post请求  提交参数
            $.post('{% url "order:commit" %}',params,function (data) {
                if (data.res==5){
                    //创建成功
                    alert('创建成功')
                    localStorage.setItem('order_finish',2);
			        $('.popup_con').fadeIn('fast', function() {

				        setTimeout(function(){
					        $('.popup_con').fadeOut('fast',function(){
						        window.location.href = '{% url "user:order" 1 %}';
					        });
				        },3000)
			        });
                }
                else {
                    alert(data.errmsg)
                }
            })
		});
	</script>
{% endblock bottomfile %}

templates/son.html
{% extends 'basetest.html' %}
{% block age %}
    {{ age }}
{% endblock age %}

templates/user_center_order.html
{% extends 'base_user_center.html' %}
{% load staticfiles %}
{% block right_content %}
		<div class="right_content clearfix">
        {% for order in order_page %}
				<h3 class="common_title2">全部订单</h3>
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.create_time }}</li>
					<li class="col02">订单号：{{ order.order_id }}</li>
					<li class="col02 stress">{{ order.status_name }}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for og in order.order_goods %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{{ og.sku.image.url }}"></li>
									<li class="col02">{{ og.sku.name }}<em>{{ og.sku.price }}元/{{ og.sku.units }}</em></li>
									<li class="col03">{{ og.count }}</li>
									<li class="col04">{{ og.price }}元</li>
								</ul>
                                {% endfor %}
							</td>
							<td width="15%">{{ order.total_price|add:order.transit_price }}(含运费：{{order.transit_price }})元</td>
							<td width="15%">{{ order.status_name }}</td>{% csrf_token %}
							<td width="15%"><a href="#" order_id="{{ order.order_id }}" status="{{ order.order_status }}" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
        {% endfor %}
				<div class="pagenation">
                {% if  order_page.has_previous %}
					<a href="{% url 'user:order' order_page.previous_page_number %}">上一页</a>
                {% endif %}
                    {% for page in pages %}
					<a href="{% url 'user:order' page %}" {% if  page == order_page.number %} class="active"{% endif %}>{{ page }}</a>
                    {% endfor %}
                {% if  order_page.has_next %}
					<a href="{% url 'user:order' order_page.next_page_number %}">下一页></a>
                {% endif %}
				</div>
		</div>
    {% block bottomfiles %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
    $('.oper_btn').each(function () {
        // 获取支付状态
        alert('获取支付状态')
        status = $(this).attr('status')
        if (status == 1){
            $(this).text('去支付')
        }
        else if (status == 4){
            $(this).text('去评价')
        }
        else if (status == 5){
            $(this).text('已完成')
        }
    })

    $('.oper_btn').click(function () {
        // 获取status
        status = $(this).attr('status')
        // 获取订单id
        order_id = $(this).attr('order_id')
        if (status == 1){
            // 进行支付
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            // 组织参数
            params = {'order_id':order_id, 'csrfmiddlewaretoken':csrf}
            // 发起ajax post请求，访问/order/pay, 传递参数:order_id
            alert('发起ajax post请求')
            $.post('{% url "order:pay" %}', params, function (data) {
                if (data.res == 3){
                    // 引导用户到支付页面
                    alert('引导用户到支付页面')
                    window.open(data.pay_url)
                    // 浏览器访问/order/check, 获取支付交易的结果
                    // ajax post 传递参数:order_id
                    $.post('{% url "order:check" %}', params, function (data){
                        if (data.res == 3){
                            alert('支付成功')
                            // 刷新页面
                            location.reload()
                        }
                        else{
                            alert(data.errmsg)
                        }
                    })
                }
                else{
                    alert(data.errmsg)
                }
            })
        }
        else if (status == 4){
            // 其他情况
            // 跳转到评价页面
            location.href = "/order/comment/"+ order_id
        }
    })
    </script>
{% endblock bottomfiles %}
{% endblock right_content %}